[package]
name = "snowflake-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
snowflake-jwt = { path = "../jwt" }
reqwest = { version = "0.11", features = ["json"] }
log = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
url = "2"
uuid = { version = "1.4", features = ["v1", "v4"] }
arrow = "42"
base64 = "0.21"
regex = "1"
object_store = { version = "0.6", features = ["aws"] }
async-trait = "0.1"

[dev-dependencies]
anyhow = "1"
env_logger = "0.10"
clap = { version = "4", features = ["derive"] }
arrow = { version = "42", features = ["prettyprint"] }
tokio = { version = "1", features=["macros", "rt-multi-thread"] }
